table_plane_extractor:
  downsample_vox_size: 0.01 # voxel size for downsampling
  max_angle_deg: 5 # maximum allowed angle (in degree) to still be considered horizontal
  min_cluster_size: 200 # min amount of points needed to form an object
  cluster_dbscan_eps: 0.1 # eps for dbscan clustering algorithm
  plane_segmentation_distance_threshold: 0.01
  base_frame: map # frame which is used for all calculations, which means
  # that the planes returned are horizontal in this frame -> should be a frame with z pointing upwards for table extractions
  z_min: 0.2 # min allowed z_coordinate for planes (used for filtering floor)

get_objects_on_table:
  z_min: 0.2 # min z coordinate of plane (relative to map frame) to be considered a valid table plane
  cluster_dbscan_eps: 0.01 # density parameter that is used to find neighboruing points for object segmentation
  min_points: 50 # minimum number of points to form a valid object-cluster
  min_volume: 0.0001 # minimum volume bounding box has to have to not be discarded